import HomePage from "./HomePage";
import AboutPage from "./AboutPage";
import ErrorPage from "./ErrorPage";
import CartPage from "./CartPage";
import ProductsPage from "./ProductsPage";
import SingleProductPage from "./SingleProductPage";
import CheckoutPage from "./CheckoutPage";
import AuthWrapper from "./AuthWrapper";
import PrivateRoute from "./PrivateRoute";
export {HomePage, AboutPage, ErrorPage, CartPage, ProductsPage, SingleProductPage, CheckoutPage, AuthWrapper, PrivateRoute};